[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Methods = "GET,HEAD,PUT,PATCH,POST,DELETE"
      Access-Control-Allow-Headers = "Authorization,Content-Type"
      X-Frame-Options = "SAMEORIGIN"
      X-Content-Type-Options = "nosniff"
      X-XSS-Protection = "1; mode=block"
      Referrer-Policy = "strict-origin-when-cross-origin"
      Content-Security-Policy = "default-src 'self'; script-src 'self' 'nonce-{RANDOM}' 'strict-dynamic'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self'; object-src 'none';"
      Permissions-Policy = "geolocation=(), microphone=(), camera=(), display-capture=(), clipboard-read=(), clipboard-write=()"